### ISSUE TITLE
Windows: Run one-off `psql` command?

### ISSUE THREAD

**Issue by karlhorky** [ikalnytskyi/action-setup-postgres#31]
Hi, thanks for this action, really great!

I've been trying to connect to PostgreSQL on Windows (`windows-latest`) via various means, including `psql` and [Postgres.js](https://github.com/porsager/postgres) (I may open another issue later for Postgres.js)

And I have been unable to find the correct syntax in my research for running a one-off `psql` database query via `-c` or `--command` flag on GitHub Actions with the `setup-postgres` action:

```yaml
name: CI
on: push

jobs:
  ci:
    name: CI
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      PGHOST: localhost
      PGDATABASE: preflight_test_project_next_js_passing
      PGUSERNAME: preflight_test_project_next_js_passing
      PGPASSWORD: preflight_test_project_next_js_passing
    steps:
      - uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{ env.PGUSERNAME }}
          password: ${{ env.PGPASSWORD }}
          database: ${{ env.PGDATABASE }}
      - uses: actions/checkout@v4

      # Run one-off psql query using -c flag:
      - run: psql -U preflight_test_project_next_js_passing -d preflight_test_project_next_js_passing -c 'SELECT 2';
```

The `psql` step just hangs (eg. in [this workflow run](https://github.com/upleveled/preflight-test-project-next-js-passing/actions/runs/8517560384/job/23354574535)):

https://github.com/ikalnytskyi/action-setup-postgres/assets/1935696/3ff3a4f1-eee7-402a-8496-d885f24ecccb

---

I've been trying various syntaxes in this PR, with no success to get it to show any output:

- https://github.com/upleveled/preflight-test-project-next-js-passing/pull/152

eg:

```yaml
      - run: psql -U preflight_test_project_next_js_passing -d preflight_test_project_next_js_passing -c 'SELECT 2';
```

```yaml
      - run: |
          & psql -U preflight_test_project_next_js_passing -d preflight_test_project_next_js_passing --command 'SELECT 2';
```

[`shell: bash`, similar as to how the action is configured](https://github.com/ikalnytskyi/action-setup-postgres/blob/ca880f61d266671e698058978c0d135c769df280/action.yml#L60)

```yaml
      - name: psql
        shell: bash
        run: |
          psql -a --echo-errors -h localhost -U preflight_test_project_next_js_passing -d preflight_test_project_next_js_passing --command 'SELECT 2'
```

**Comment by karlhorky** [comment]
Ah, I think it appears that `psql` is hanging on the prompt for the password 🤔 (even though GitHub Actions is a non-TTY environment)

Apparently `psql` will not read the existing `PGPASSWORD` environment variable from the GitHub Actions env config block:

```yaml
    env:
      PGHOST: localhost
      PGDATABASE: preflight_test_project_next_js_passing
      PGUSERNAME: preflight_test_project_next_js_passing
      # 💥 This will not be read by psql, which will lead to the hanging behavior as it waits for a password to be entered
      PGPASSWORD: preflight_test_project_next_js_passing
```

Adding an explicit `PGPASSWORD=<password>` to the start of the line (with `shell:bash`) seems to work:

```
      - name: psql
        shell: bash
        run: |
          PGPASSWORD=preflight_test_project_next_js_passing psql -a --echo-errors -h localhost -U preflight_test_project_next_js_passing -d preflight_test_project_next_js_passing --command 'SELECT 2'
```

Output:

```
Run psql
  PGPASSWORD=preflight_test_project_next_js_passing psql -a --echo-errors -h localhost -U preflight_test_project_next_js_passing -d preflight_test_project_next_js_passing --command 'SELECT 2'
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    PGHOST: localhost
    PGDATABASE: preflight_test_project_next_js_passing
    PGUSERNAME: preflight_test_project_next_js_passing
    PGPASSWORD: 
    PQ_LIB_DIR: C:\Program Files\PostgreSQL\14\lib
    PGROOT: 
    PGDATA: 
    PGBIN: 
    PGUSER: 
    PGSERVICEFILE: D:\a\_temp/pgdata/pg_service.conf

 ?column? 
----------
        2
(1 row)
```

Closing.
